%    MIDAS-VT-Pre Copyright (C) 2018  Keyvan Zare-Rami
%
%    This program is free software: you can redistribute it and/or modify
%    it under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.
%
%    This program is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%
%    You should have received a copy of the GNU General Public License
%    along with this program.  If not, see <https://www.gnu.org/licenses/>.

global ...
... GUI_Start_Preprocessor
ModelGenModeIndex...
...MAIN1
EnableCohELIndex...
...Image2Shape
BoundXY...
...Shape2GEom
dl ...
...Geom2Mesh
Coo_O Con_O NumRegEl El_Phase1 El_Phase2 El_CZ ...
... AddCohEl
CohEl_Phase1 CohEl_Phase2 CohEl_InterPhase12...
... Geometry
TestType... 
Dim_w Dim_h Dim_a Dim_b Dim_CZw Dim_CZh Dim_nw Dim_nl ...
... Microstructure
HeteroIndex...
MixtureImageName MixtureImagePath...
SegmentationThreshold MinFineParticleSize ConvexingFactor ...
...Mesh
isForMIDAS ...
JigglingIndex MaxMeshSize MeshGrowthRate JigglingMaxIter...
... Boundary Condition
TT_T    TT_B	TT_L    TT_R...
ST_T	ST_B...
TPBT_LS	TPBT_RS	TPBT_LP...
FPBT_LS	FPBT_RS	FPBT_LLP	FPBT_RLP...
SCBT_LS	SCBT_RS	SCBT_LP...
ITT_BS	ITT_TLP	...
...RCM
BandWidth...
...GUI MAIN 2
FilePath FileName Delimiter...
... Write Output
OutputFileName
